dist: xenial
language: python
python:
  "3.7"
services:
  - postgresql

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

before_script:
  - createdb TEMPLATE

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest
  - pipenv run flake8

cache:
  directories:
    - ".venv"
